// GLOBAL
export const LANG = "LANG";
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const ADD_VISITOR = 'ADD_VISITOR';
export const REQUEST_CONSULTATION = 'REQUEST_CONSULTATION';

// USER
export const AUTH = 'AUTH';

// PAGES
export const FETCH_PAGE = 'FETCH_PAGE';
export const FETCH_PAGES = 'FETCH_PAGES';
export const CLEAR_PAGE = 'CLEAR_PAGE';
export const FETCH_TEXTS = 'FETCH_TEXTS';


// ADMIN
export const FETCH_VISITORS = 'FETCH_VISITORS';
export const FETCH_CONSULTATION_REQUESTS = 'FETCH_CONSULTATION_REQUESTS';